services:
  backend:
    container_name: acs-backend
    build:
      context: .
      dockerfile: Dockerfile
#      backend 這個容器 依賴其他服務先啟動（啟動順序），但不保證它們已經「可連線」
    image: ${DOCKER_REGISTRY}/acs-frontend:${IMAGE_TAG}
    depends_on:
      - db
      - redis
      - mqtt
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_MQTT_BROKER: ${SPRING_MQTT_BROKER}
    ports:
      - "8080:8080"

  frontend:
    container_name: acs-frontend
    build:
      context: ./acs-frontend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/acs-frontend:${IMAGE_TAG}
    ports:
      - "4200:80"
    depends_on:
      - db
      - redis
      - mqtt

  simulator:
    container_name: acs-python-simulator
    build:
      context: ./python-simulator
      dockerfile: Dockerfile
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    depends_on:
      - db
      - redis
      - mqtt

  db:
    container_name: acs-db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # 把「目前 docker-compose.yml 所在資料夾下的 DB 資料夾」掛載進 PostgreSQL container 的 /docker-entrypoint-initdb.d 資料夾中
      - ./DB:/docker-entrypoint-initdb.d
#      把 PostgreSQL 的資料儲存位置掛到 volume pgdata（讓資料不會因 container 重啟而遺失）
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: acs-redis
    image: redis:7
    ports:
      - "6379:6379"

  mqtt:
    container_name: acs-mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

# 哪些資料要持久化（避免 container 關掉資料就不見）
volumes:
  postgres_data:
