services:
  backend:
    container_name: acs-backend
    build:
      context: .
      dockerfile: ./acs-backend/Dockerfile
#    image: ${DOCKER_REGISTRY}/acs-backend:${IMAGE_TAG}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_MQTT_BROKER: ${SPRING_MQTT_BROKER}
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    networks:
      - acs_net

  frontend:
    container_name: acs-frontend
    build:
      context: ./acs-frontend
      dockerfile: ./acs-frontend/Dockerfile
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - acs_net

  simulator:
    container_name: acs-simulator
    build:
      context: ./simulator
      dockerfile: ./simulator/Dockerfile
#    image: ${DOCKER_REGISTRY}/acs-simulator:${IMAGE_TAG}
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - acs_net

networks:
  acs_net:
    external: true