services:
  backend:
    container_name: acs-backend
    image: ${DOCKER_REGISTRY}/acs-backend:${IMAGE_TAG}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_MQTT_BROKER: ${SPRING_MQTT_BROKER}
      JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m -XX:+UseG1GC"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    networks:
      - acs_net

  frontend:
    container_name: acs-frontend
    image: ${DOCKER_REGISTRY}/acs-frontend:${IMAGE_TAG}
#    ports:
#      - "4200:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - acs_net

  simulator:
    container_name: acs-simulator
    image: ${DOCKER_REGISTRY}/acs-simulator:${IMAGE_TAG}
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    networks:
      - acs_net

  nginx:
    container_name: acs-nginx
    image: nginx:stable-alpine
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./acs-frontend/dist/acs-frontend/browser:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - acs_net

networks:
  acs_net:
    external: true